[build-system]
requires = [
    'flit_core >=3.1,<4',
    'setuptools_scm',
    'pytoml',
    'importlib_metadata>=0.7; python_version < "3.8"',
    'packaging',
]
build-backend = "setuptools.build_meta"